# This is a basic workflow to help you get started with Actions
name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 2  # Fetch the last two commits

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: git status
        run: |
          git status

      - name: git log
        run: |
          git log

      - name: git diff
        id: check_deployment_yaml
        run: |
          git diff-tree --no-commit-id --name-only -r HEAD^2

      - name: Check if run.py changed
        run: |
          set +e
          git diff-tree --no-commit-id --name-only -r HEAD^2 | grep -q 'run.py'
          if [ $? -eq 0 ]; then
            echo "run.py has changed."
            echo "run_changed=true" >> $GITHUB_ENV
          else
            echo "run.py has not changed."
            echo "run_changed=false" >> $GITHUB_ENV
          fi
          set -e


      - name: Run run.py if run.py is changed        
        if: ${{ env.run_changed == 'true' }}
        run: |
          python run.py Siddharth

      - name: Run run2.py if run.py is not changed
        if: ${{ env.run_changed == 'false' }}
        run: |
          python run2.py Applepie
