# This is a basic workflow to help you get started with Actions
name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if run.py changed
        run: |
          echo "Checking for changes in run.py..."
          git fetch origin main

          # Get the latest commit hash from the main branch
          LATEST_COMMIT=$(git rev-parse FETCH_HEAD)

          # Get the previous commit hash
          PREVIOUS_COMMIT=$(git rev-parse FETCH_HEAD^)

          # Check if run.py has changed between the two commits
          if git diff --name-only $PREVIOUS_COMMIT $LATEST_COMMIT | grep -q 'run.py'; then
            echo "run_changed=true" >> $GITHUB_ENV
          else
            echo "run_changed=false" >> $GITHUB_ENV


      - name: Run run.py if run.py is changed        
        if: env.run_changed == 'true'
        run: |
          python run.py Siddharth

      - name: Run run2.py if run.py is not changed
        if: env.run_changed == 'false'
        run: |
          python run2.py Applepie
